apiVersion: batch/v1
kind: Job
metadata:
  name: ginrummy
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: ginrummy
    spec:
      containers:
      - image: jmmaloney4/sigra:latest
        imagePullPolicy: Always
        name: ginrummy
        resources:
          requests:
            cpu: "6000m"
          limits:
            cpu: "12000m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /siftagent/results/
          name: results
          subPath: 01/
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: ginrummygames
